// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDefaultCasePath() {
  return window['go']['app']['App']['GetDefaultCasePath']();
}

export function GetFindings() {
  return window['go']['app']['App']['GetFindings']();
}

export function GetTimeline(arg1) {
  return window['go']['app']['App']['GetTimeline'](arg1);
}

export function Greet(arg1) {
  return window['go']['app']['App']['Greet'](arg1);
}

export function Log(arg1, arg2, arg3) {
  return window['go']['app']['App']['Log'](arg1, arg2, arg3);
}

export function OpenCase(arg1) {
  return window['go']['app']['App']['OpenCase'](arg1);
}

export function ResetCase() {
  return window['go']['app']['App']['ResetCase']();
}

export function RunAnalysis() {
  return window['go']['app']['App']['RunAnalysis']();
}

export function StartTriage(arg1, arg2, arg3) {
  return window['go']['app']['App']['StartTriage'](arg1, arg2, arg3);
}
