// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {storage} from '../models';
import {model} from '../models';
import {app} from '../models';

export function BrowseEvidencePath():Promise<string>;

export function ExecuteSQLQuery(arg1:string):Promise<Array<Record<string, any>>>;

export function GetDefaultCasePath():Promise<string>;

export function GetEventStats():Promise<storage.EventStats>;

export function GetFindings():Promise<Array<model.Finding>>;

export function GetSystemInfo():Promise<app.SystemInfo>;

export function GetTimeline(arg1:number):Promise<Array<model.TimelineEvent>>;

export function GetTotalEventCount():Promise<number>;

export function Log(arg1:string,arg2:string,arg3:Array<any>):Promise<void>;

export function OpenCase(arg1:string):Promise<void>;

export function ResetCase():Promise<void>;

export function RunAnalysis():Promise<number>;

export function RunSelfTest():Promise<string>;

export function SearchEvents(arg1:string,arg2:number,arg3:number,arg4:string,arg5:string):Promise<Array<model.TimelineEvent>>;

export function StartTriage(arg1:string,arg2:Array<string>,arg3:Record<string, any>):Promise<void>;
