// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowseEvidencePath() {
  return window['go']['app']['App']['BrowseEvidencePath']();
}

export function ExecuteSQLQuery(arg1) {
  return window['go']['app']['App']['ExecuteSQLQuery'](arg1);
}

export function GetDefaultCasePath() {
  return window['go']['app']['App']['GetDefaultCasePath']();
}

export function GetEventStats() {
  return window['go']['app']['App']['GetEventStats']();
}

export function GetFindings() {
  return window['go']['app']['App']['GetFindings']();
}

export function GetSystemInfo() {
  return window['go']['app']['App']['GetSystemInfo']();
}

export function GetTimeline(arg1) {
  return window['go']['app']['App']['GetTimeline'](arg1);
}

export function GetTotalEventCount() {
  return window['go']['app']['App']['GetTotalEventCount']();
}

export function Log(arg1, arg2, arg3) {
  return window['go']['app']['App']['Log'](arg1, arg2, arg3);
}

export function OpenCase(arg1) {
  return window['go']['app']['App']['OpenCase'](arg1);
}

export function ResetCase() {
  return window['go']['app']['App']['ResetCase']();
}

export function RunAnalysis() {
  return window['go']['app']['App']['RunAnalysis']();
}

export function RunSelfTest() {
  return window['go']['app']['App']['RunSelfTest']();
}

export function SearchEvents(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['SearchEvents'](arg1, arg2, arg3, arg4, arg5);
}

export function StartTriage(arg1, arg2, arg3) {
  return window['go']['app']['App']['StartTriage'](arg1, arg2, arg3);
}
